name: Create Release Draft
on: workflow_dispatch

jobs:
  publish:
    uses: ./.github/workflows/publish-solution.yml

  create_release_draft:
    needs: [ publish ]
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Print Artifacts (Debug only)
        if: runner.debug == '1'
        run: tree artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ needs.publish.outputs.version }}"
          tag_name: "v${{ needs.publish.outputs.version }}"
          body: "TODO: Write changelog"
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: artifacts/*/*.zip